baseURL = 'https://www.liamatt.dev'
languageCode = 'en-us'
title = 'Liam Attard'
theme = 'profile'
enableRobotsTXT = true

[[menus.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10
[[menus.main]]
  identifier = "Home"
  name = "Home"
  url = "/"
  weight = 10

[params.navbar]
align = "ms-auto"
disableSearch = true
enableSeparator = false

[params.hero]
enable = true
intro = "Hello!"
title = "I'm Liam"
subtitle = "A Software Engineer"
content = "From Malta 🇲🇹, living in Luxembourg 🇱🇺"
image = "/images/hero.svg"

[params.hero.button]
  enable = true
  name = "Download My Resume"
  url = "LiamAtt_Resume.pdf"
  download = true
  newPage = false

[params.color]
  primaryColor = "#93C572"
  backgroundColor = "#ebe6e9"

[params.theme]
  disableThemeToggle = true
  defaultTheme="light"


[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/liam-attard-1542b6180"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/liamattard/"


[params]
  favicon = "favicon.ico"

[params.footer.socialNetworks]
  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = false

  [params.singlePages.readTime]
    enable = false