baseURL = 'https://www.liamatt.dev'
languageCode = 'en-us'
title = 'Liam Attard'

theme = 'profile'

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1


[params]

  [params.navbar]
  align = "ms-auto"
  disableSearch = true
  enableSeparator = false

  [params.hero]
  enable = true
  intro = "Hello World!"
  title = "I'm Liam"
  subtitle = "Software Engineer from 🇲🇹"
  content = "I like to use Linux, ZSH, Neovim, Tmux, Java, Python"
  image = "/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "Download my resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin-in"
url = "https://example.com"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://example.com"

